### ISSUE TITLE
VORP Clothing Stores 

### ISSUE THREAD

**Issue by samuelswandi** [VORPCORE/vorp_clothingstores-lua#13]
Hi team!

When I first used this pre-made, even though that it runs perfectly, there is an error caused by `ensure vorp_clothingstores` because the resource is not found. 

![image](https://github.com/VORPCORE/vorp_clothingstores-lua/assets/79347993/31cfa308-2f18-4ca5-83e7-fb72c354985d)

I can make a PR to solve this though. Thanks!

**Comment by outsider31000** [comment]
yes we removed it , character script now has the clothing stores.

**Comment by samuelswandi** [comment]
oh, then can we remove the "ensure vorp_clothingstores"?

**Comment by outsider31000** [comment]
yes you can remove
